import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import HeroImage from '../components/HeroImage'
import s from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={s.container}>
      <Head>
        <title>Frontend Mentor | Home Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon-32x32.png' />
      </Head>

      <main className={s.main}>
        <div className={s.showcaseSection}>
          <div className={s.heroSection}>
            <HeroImage />
            <div className={s.trendingSection}>
              <h1>The Bright Future of Web 3.0?</h1>
              <div>
                <p>
                  We dive into the next evolution of the web that claims to put
                  the power of the platforms back into the hands of the people.
                  But is it really fulfilling its promise?
                </p>
                <Link href='#' className={s.button}>
                  Read more
                </Link>
              </div>
            </div>
          </div>
          <div className={s.newSection}>
            <h1>New</h1>
            <h2>Hydrogen VS Electric Cars</h2>
            <p>Will hydrogen-fueled cars ever catch up to EVs?</p>
            <h2>The Downsides of AI Artistry</h2>
            <p>
              What are the possible adverse effects of on-demand AI image
              generation?
            </p>
            <h2>Is VC Funding Drying Up?</h2>
            <p>
              Private funding by VC firms is down 50% YOY. We take a look at
              what that means.
            </p>
          </div>
        </div>
        <div className={s.popularCard}></div>
      </main>
    </div>
  )
}
