import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import HeroImage from '../components/HeroImage'
import s from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={s.container}>
      <Head>
        <title>Frontend Mentor | Home Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon-32x32.png' />
      </Head>

      <main className={s.main}>
        <div className={s.showcaseSection}>
          <div className={s.heroSection}>
            <HeroImage />
            <div className={s.trendingSection}>
              <h1>The Bright Future of Web 3.0?</h1>
              <p>
                We dive into the next evolution of the web that claims to put
                the power of the platforms back into the hands of the people.
                But is it really fulfilling its promise?
              </p>
              <Link href='#' className={s.button}>
                Read more
              </Link>
            </div>
          </div>
          <div className={s.newSection}></div>
        </div>
        <div className={s.popularCard}></div>
      </main>
    </div>
  )
}
